spring:
  application:
    name: NanoLinkGenerator
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: pkc-41p56.asia-south1.gcp.confluent.cloud:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: nanoLinkTopic
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              package:
                com.harshit.NanoLinkWriter.model
    properties:
      session:
        timeout:
          ms: 45000
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='3IE23ZGYFSWOT4QW' password='cfltvWm8pKCB0xqvDnWr1SJqZkGKhEcnJNh9Nf0YQI03tB9eKrvYerB1i/6GzZZQ';

client:
  id: ccloud-springboot-client-8aa9d2a7-bf08-4a59-805c-af79d1a6daf0

